"""Builds every GoodNight icon and store graphic from one source image.

    python scripts/make-icons.py

Source: store/icon-source.png (square artwork on a flat indigo background).
Writes:
- Android launcher icons: legacy PNGs plus an adaptive icon (foreground on the
  source's background colour) with a themed/monochrome layer
- ic_notification: white silhouette for notifications (local, alarm, push)
- splash_logo + launch_background: the start-up splash
- assets/logo.png: the logo shown inside the app
- store/icon-512.png and store/feature-graphic.png for Google Play
"""
from pathlib import Path
from statistics import median

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parent.parent
RES = ROOT / 'android/app/src/main/res'
STORE = ROOT / 'store'
SOURCE = STORE / 'icon-source.png'

DENSITIES = {'mdpi': 1, 'hdpi': 1.5, 'xhdpi': 2, 'xxhdpi': 3, 'xxxhdpi': 4}
GOLD = (253, 226, 155)


def background_colour(img):
    """Median colour of the outer border, which is the flat background."""
    w, h = img.size
    px = img.load()
    edge = [px[x, y] for x in range(w) for y in (0, 1, h - 2, h - 1)]
    edge += [px[x, y] for y in range(h) for x in (0, 1, w - 2, w - 1)]
    return tuple(round(median(c[i] for c in edge)) for i in range(3))


def key_out(img, bg, soft=60.0):
    """Turns the background transparent, keeping anti-aliased edges smooth."""
    out = Image.new('RGBA', img.size)
    src, dst = img.load(), out.load()
    for y in range(img.size[1]):
        for x in range(img.size[0]):
            r, g, b = src[x, y][:3]
            dist = ((r - bg[0]) ** 2 + (g - bg[1]) ** 2 + (b - bg[2]) ** 2) ** 0.5
            a = min(1.0, max(0.0, (dist - 12) / soft))
            if a == 0:
                dst[x, y] = (0, 0, 0, 0)
                continue
            # Remove the background that was blended into edge pixels.
            c = [min(255, max(0, round((v - (1 - a) * bv) / a))) for v, bv in zip((r, g, b), bg)]
            dst[x, y] = (*c, round(a * 255))
    return out


def centred(art, canvas, fill):
    """[art] scaled so its visible part spans [fill] of a square canvas."""
    box = art.getbbox()
    crop = art.crop(box)
    scale = fill * canvas / max(crop.size)
    crop = crop.resize((max(1, round(crop.width * scale)), max(1, round(crop.height * scale))), Image.LANCZOS)
    out = Image.new('RGBA', (canvas, canvas), (0, 0, 0, 0))
    out.paste(crop, ((canvas - crop.width) // 2, (canvas - crop.height) // 2), crop)
    return out


def rounded(img, radius):
    m = Image.new('L', (img.width * 4, img.height * 4), 0)
    ImageDraw.Draw(m).rounded_rectangle([0, 0, m.width - 1, m.height - 1], radius=radius * 4, fill=255)
    out = img.convert('RGBA')
    out.putalpha(m.resize(img.size, Image.LANCZOS))
    return out


def white(art):
    out = Image.new('RGBA', art.size, (255, 255, 255, 0))
    out.putalpha(art.split()[3])
    return out


def write_android(source, art, bg):
    for name, s in DENSITIES.items():
        mip = RES / f'mipmap-{name}'
        mip.mkdir(parents=True, exist_ok=True)
        size = round(48 * s)
        rounded(source.resize((size, size), Image.LANCZOS), size * 0.22).save(mip / 'ic_launcher.png')
        # 108dp canvas; round masks keep a 66dp circle, so the art spans ~56%.
        centred(art, round(108 * s), 0.56).save(mip / 'ic_launcher_foreground.png')

        draw = RES / f'drawable-{name}'
        draw.mkdir(parents=True, exist_ok=True)
        white(centred(art, round(24 * s), 0.92)).save(draw / 'ic_notification.png')
        centred(art, round(160 * s), 1.0).save(draw / 'splash_logo.png')

    anydpi = RES / 'mipmap-anydpi-v26'
    anydpi.mkdir(exist_ok=True)
    (anydpi / 'ic_launcher.xml').write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
        '    <background android:drawable="@color/ic_launcher_background" />\n'
        '    <foreground android:drawable="@mipmap/ic_launcher_foreground" />\n'
        '    <monochrome android:drawable="@mipmap/ic_launcher_foreground" />\n'
        '</adaptive-icon>\n', encoding='utf-8')
    (RES / 'values/ic_launcher_background.xml').write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n<resources>\n'
        '    <color name="ic_launcher_background">#%02X%02X%02X</color>\n'
        '</resources>\n' % bg, encoding='utf-8')
    splash = (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- Generated by scripts/make-icons.py: logo on the icon background. -->\n'
        '<layer-list xmlns:android="http://schemas.android.com/apk/res/android">\n'
        '    <item android:drawable="@color/ic_launcher_background" />\n'
        '    <item>\n'
        '        <bitmap android:gravity="center" android:src="@drawable/splash_logo" />\n'
        '    </item>\n'
        '</layer-list>\n')
    for folder in ('drawable', 'drawable-v21'):
        (RES / folder / 'launch_background.xml').write_text(splash, encoding='utf-8')


def font(size, bold=False):
    names = ['segoeuib.ttf', 'arialbd.ttf', 'DejaVuSans-Bold.ttf'] if bold else ['segoeui.ttf', 'arial.ttf', 'DejaVuSans.ttf']
    for name in names:
        for base in ('C:/Windows/Fonts', '/usr/share/fonts/truetype/dejavu', '/Library/Fonts'):
            p = Path(base) / name
            if p.exists():
                return ImageFont.truetype(str(p), size)
    return ImageFont.load_default()


def write_store(source, art, bg):
    source.resize((512, 512), Image.LANCZOS).save(STORE / 'icon-512.png')

    w, h = 1024, 500
    img = Image.new('RGBA', (w, h), bg + (255,))
    logo = centred(art, 400, 1.0)
    img.alpha_composite(logo, (50, 50))
    d = ImageDraw.Draw(img)
    d.text((480, 150), 'GoodNight', font=font(96, bold=True), fill=(255, 255, 255))
    d.text((484, 268), 'A sleep pact for two', font=font(44), fill=GOLD)
    d.text((484, 330), 'Agree on bedtimes. Keep the streak.', font=font(30), fill=(205, 205, 235))
    img.convert('RGB').save(STORE / 'feature-graphic.png')


def write_flutter(art):
    (ROOT / 'assets').mkdir(exist_ok=True)
    centred(art, 512, 1.0).save(ROOT / 'assets/logo.png')


if __name__ == '__main__':
    source = Image.open(SOURCE).convert('RGB')
    bg = background_colour(source)
    art = key_out(source, bg)
    write_android(source, art, bg)
    write_store(source, art, bg)
    write_flutter(art)
    print('Background #%02X%02X%02X; icons written.' % bg)
